#!/usr/bin/env bash
DIR="$( cd $(dirname "${0}") && pwd )"
rm -rf ${DIR}/vim/backup/* ${DIR}/vim/swaps/*
cd ${DIR} && ./mode ro
cd ${DIR} && tar --exclude=*.gz -f pack.tar.gz -cv .
cd ${DIR} && ./mode rw
