#!/bin/bash
DIR="$( cd $(dirname "${0}")/.. && pwd )"
rm -rf ${DIR}/utils/completion-ruby
git clone git://github.com/mernen/completion-ruby.git ${DIR}/utils/completion-ruby
cd ${DIR}/bash_completion.d && ln -sf ../utils/completion-ruby/completion* ./

